const MOBILE_PADDING_MIN = '4px';
const MOBILE_PADDING_MAX = '12px';
const MOBILE_PADDING_SCALE = '2vw';
const MOBILE_TABLE_MIN_CELL_WIDTH = 96;

export const MOBILE_PADDING = `clamp(${MOBILE_PADDING_MIN}, ${MOBILE_PADDING_SCALE}, ${MOBILE_PADDING_MAX})`;
export const MOBILE_BREAKPOINT = '768px';
export const MOBILE_TABLE_MIN_COLUMN_WIDTH = MOBILE_TABLE_MIN_CELL_WIDTH;
